name: JB_Tax_Web

env:
  AZURE_WEBAPP_NAME: jb-tax-web # the web app name
  AZURE_RESOURCE_GROUP: RameyRoad-PPM # the resource group name
  CONTAINER_NAME: clients/jbtax-web # the container name
  SLOT_NAME: staging
  BRANCH_NAME: ${GITHUB_REF##*/}
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

on:
  push:
    branches: ["dev", "main"]
    paths:
      - ".github/workflows/web-docker.yml" # when this script changes
      - "jb-tax-next/**" # when the Web app changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v3

      - name: Login via Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: Build and push image
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_LOGIN_SERVER }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - run: |
          docker build ./jbtax-next -f jbtax-next/Dockerfile -t ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.CONTAINER_NAME }}:${{ env.BRANCH_NAME }}-${{ github.run_id }}
          docker push ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.CONTAINER_NAME }}:${{ env.BRANCH_NAME }}-${{ github.run_id }}

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@0b651ed7546ecfc75024011f76944cb9b381ef1e

        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: "${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.CONTAINER_NAME }}:main-${{ github.run_id }}"

      - name: Run Azure PowerShell script
        uses: azure/powershell@v1
        with:
          inlineScript: |
            az webapp restart --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }}
          azPSVersion: "latest"
