name: JB_Tax_Web

env:
  AZURE_WEBAPP_NAME: rameyroad-jbtax-eus-01 # the web app name
  AZURE_RESOURCE_GROUP: jbtax # the resource group name
  CONTAINER_NAME: clients/jbtax-web # the container name
  SLOT_NAME: staging
  BRANCH_NAME: ${GITHUB_REF##*/}

on:
  push:
    branches: ["main"]
    tags:
      - "v*" # v1.0.0, v1.0.1, etc.
    paths:
      - ".github/workflows/web-docker.yml" # when this script changes
      - "jbtax-next/**" # when the Web app changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check if the secret is present
      - name: Check if secret is set
        run: |
          if [ -z "${{ secrets.AZURE_CREDENTIALS }}" ]; then
            echo "MY_SECRET is not set. Stopping the build gracefully..."
            exit 0  # Exit the build gracefully
          fi

      - name: Checkout GitHub Action
        uses: actions/checkout@v3

      - name: Login via Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push image
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          docker build ./jbtax-next -f jbtax-next/Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.CONTAINER_NAME }}:${{ env.BRANCH_NAME }}-${{ github.run_id }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.CONTAINER_NAME }}:${{ env.BRANCH_NAME }}-${{ github.run_id }}

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@0b651ed7546ecfc75024011f76944cb9b381ef1e

        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: "${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.CONTAINER_NAME }}:main-${{ github.run_id }}"

      - name: Run Azure PowerShell script
        uses: azure/powershell@v1
        with:
          inlineScript: |
            az webapp restart --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }}
          azPSVersion: "latest"
